version: 2.0
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            python setup.py test
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "30 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
